// 'use client'

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NavbarDemo } from "@/components/Navbar";
import Footer from "@/components/Footer";
import AuthProvider from "./context/AuthProvider";
import { useEffect } from "react";
import { testConnection } from "@/lib/dbConnect";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Boring Books ",
  description: 'Generated by create next app and developed by Devaliance, this project is an e-library built using Next.js, providing a seamless digital platform for accessing and managing books online.',

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    // Test the database connection when the app initializes
    testConnection()
      .then(() => console.log("Database connected successfully"))
      .catch((error) => {
        console.error("Error during DB connection:", error.message);
        process.exit(1); // Optional: terminate if connection fails
      });
  }, []);
  return (
    <html lang="en">
    <AuthProvider>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex mt-[2rem]">
        < NavbarDemo />
        </div>
        {children}
        < Footer />
      </body>
      </AuthProvider>
    </html>
  );
}
